In [2]:
import pandas as pd
import os

### W tym Notebooku dokonano zaczytania danych dotyczcych jakości powietrza.
### z archiwum Głównego Inspektoratu Ochrony Środowiska.
Zastosowano następujace kroki:
- Zaczytanie danych z pliku źródłowego dla wybranych zanieczyszczeń 
- Wybrano badane stacje pomiarowe w wybranych miastach
- utworzono Data Frame dla wybranych kolunm oraz odpowienio opisano kolumny.
- Eksport jako Raw_data do plików .csv 


źródło : https://powietrze.gios.gov.pl/pjp/archives

## LISTA STACJI PL WG KODU

| Kod stacji            | Miasto                |
|----------------------|----------------------|
| DsChojnowMalMOB      | Chojnów              |
| DsJelGorOgin         | Jelenia Góra         |
| DsKlodzSzkol         | Kłodzko              |
| DsKudowaSzkoMOB      | Kudowa-Zdrój         |
| DsWrocAlWisn         | Wrocław              |
| DsWrocWybCon         | Wrocław              |
| KpBydPlPozna         | Bydgoszcz            |
| KpBydWarszaw         | Bydgoszcz            |
| KpNaklWawrzy         | Nakło nad Notecią    |
| KpSwiecJPawlMOB      | Świecie              |
| KpToruKaszow         | Toruń                |
| KpWloclOkrze         | Włocławek            |
| LbLubObywate         | Lublin               |
| LbLukBulNiepMOB      | Łuków                |
| LbZamoHrubie         | Zamość               |
| LdKutn1Maja7MOB      | Kutno                |
| LdLaskNarutoMOB      | Łask                 |
| LdLodzCzerni         | Łódź                 |
| LdRadomsRoln         | Radomsko             |
| LdZgieMielcz         | Zgierz               |
| LuGorzKosGdy         | Gorzów Wielkopolski  |
| LuLubsStrzelMOB      | Lubsko               |
| LuWsKaziWiel         | Wschowa              |
| LuZarySzyman         | Żary                 |
| LuZielKrotka         | Zielona Góra         |
| MpKrakAlKras         | Kraków               |
| MpKrakBulwar         | Kraków               |
| MpTarRoSitko         | Tarnów               |
| MzBialaKmiciMOB      | Biała Podlaska       |
| MzKonJezZero         | Konstancin-Jeziorna  |
| MzLegZegrzyn         | Legionowo            |
| MzOtwoBrzozo         | Otwock               |
| MzPiasPulask         | Piaseczno            |
| MzPlocMiReja         | Płock                |
| MzPultuskMicMOB      | Pułtusk              |
| MzRadTochter         | Radom                |
| MzSiedKonars         | Siedlce              |
| MzWarAlNiepo         | Warszawa             |
| MzWarBajkowa         | Warszawa             |
| MzWarChrosci         | Warszawa             |
| MzWarKondrat         | Warszawa             |
| MzWarTolstoj         | Warszawa             |
| MzWarWokalna         | Warszawa             |
| MzZyraRoosev         | Żyrardów             |
| OpKKozBSmial         | Kędzierzyn-Koźle     |
| OpOpoleKoszy         | Opole                |
| OpStrzOpWyszMOB      | Strzelce Opolskie    |
| PdAugustowUz         | Augustów             |
| PdBialAlPils         | Białystok            |
| PdBialPPiech         | Białystok            |
| PdBialUpalna         | Białystok            |
| PdBorsukowiz         | Borsukowizna         |
| PdGrajewoWPoMOB      | Grajewo              |
| PdSuwPulask2         | Suwałki              |
| PkBoguchAngeMOB      | Boguchwała           |
| PkDebiGrottg         | Dębica               |
| PkJarosPruch         | Jarosław             |
| PkJasloSikor         | Jasło                |
| PkKrosKletow         | Krosno               |
| PkMielBierna         | Mielec               |
| PkNiskoSzkla         | Nisko                |
| PkPrzemGrunw         | Przemyśl             |
| PkRymZdrPark         | Rymanów-Zdrój        |
| PkRzeszPilsu         | Rzeszów              |
| PkRzeszSloci         | Rzeszów              |
| PkRzeszStarz         | Rzeszów              |
| PmBytowMila1MOB      | Bytów                |
| PmGdaLeczkow         | Gdańsk               |
| PmGdaWyzwole         | Gdańsk               |
| PmGdyPorebsk         | Gdynia               |
| PmKosTargowa         | Kościerzyna          |
| PmSopBiPlowc         | Sopot                |
| SkLagowZaploMOB      | Łagów                |
| SkPolaRuszcz         | Połaniec             |
| SkSkarz1MajaMOB      | Skarżysko-Kamienna   |
| SkStaraZlota         | Starachowice         |
| SlBielPartyz         | Bielsko-Biała        |
| SlGoczaUzdroMOB      | Goczałkowice-Zdrój   |
| SlJastrZdroj         | Jastrzębie-Zdrój     |
| SlKatoKossut         | Katowice             |
| SlKatoPlebA4         | Katowice             |
| SlRaciborzWPMOB      | Racibórz             |
| SlZlotPotLes         | Złoty Potok          |
| SlZywieKoper         | Żywiec               |
| WmDzialPolnaMOB      | Działdowo            |
| WmElbBazynsk         | Elbląg               |
| WmElkStadion         | Ełk                  |
| WmOlsPuszkin         | Olsztyn              |
| WpKaliSawick         | Kalisz               |
| WpKoscianMayMOB      | Kościan              |
| WpPoznDabrow         | Poznań               |
| WpPoznSzwajc         | Poznań               |
| ZpDabkiSztorMOB      | Dąbki                |
| ZpKolZolkiew         | Kołobrzeg            |
| ZpSzczAndrze         | Szczecin             |
| ZpSzczPilsud         | Szczecin             |

| Kod stacji        | Lokalizacja (miasto + przybliżone miejsce) | Województwo |
|-------------------|-------------------------------------------|-------------|
| DsChojnowMalMOB   | Chojnów (mobilna)                         | dolnośląskie |
| DsCzerStraza      | Czerna / Straża                           | dolnośląskie |
| DsDziePilsud      | Dzierżoniów, ul. Piłsudskiego             | dolnośląskie |
| DsJelGorOgin      | Jelenia Góra, ul. Ogińskiego              | dolnośląskie |
| DsKlodzSzkol      | Kłodzko, okolice szkoły                   | dolnośląskie |
| DsKudowaSzkoMOB   | Kudowa-Zdrój (mobilna)                    | dolnośląskie |
| DsLegAlRzecz      | Legnica, al. Rzeczypospolitej             | dolnośląskie |
| DsNowRudJezi      | Nowa Ruda, ul. Jeziorna                   | dolnośląskie |
| DsOlawZolnAK      | Oława, ul. Żołnierzy AK                   | dolnośląskie |
| DsStrzegomMOB     | Strzegom (mobilna)                        | dolnośląskie |
| DsTrzebniMaj      | Trzebnica, ul. 3 Maja                     | dolnośląskie |
| DsWalbrzWyso      | Wałbrzych, ul. Wysockiego                 | dolnośląskie |
| DsWrocWybCon      | Wrocław, ul. Wyb. Conrada-Korzeniowskiego | dolnośląskie |
| KpBydPlPozna      | Bydgoszcz, pl. Poznański                  | kujawsko-pomorskie |
| KpBydWarszaw      | Bydgoszcz, ul. Warszawska                 | kujawsko-pomorskie |
| KpGrudPilsud      | Grudziądz, ul. Piłsudskiego               | kujawsko-pomorskie |
| KpInowSolank      | Inowrocław, Solanki                       | kujawsko-pomorskie |
| KpNaklWawrzy      | Nakło nad Notecią, ul. Wawrzyniaka        | kujawsko-pomorskie |
| KpSwiecJPawlMOB   | Świecie (mobilna)                         | kujawsko-pomorskie |
| KpToruDziewu      | Toruń, ul. Dziewulskiego                  | kujawsko-pomorskie |
| KpToruKaszow      | Toruń, ul. Kaszownika                     | kujawsko-pomorskie |
| KpToruWSikor      | Toruń, ul. W. Sikorskiego                 | kujawsko-pomorskie |
| KpWloclKalis      | Włocławek, ul. Kaliska                    | kujawsko-pomorskie |
| KpWloclOkrze      | Włocławek, ul. Okrzei                     | kujawsko-pomorskie |
| MpKrakAlKras      | Kraków, al. Krasińskiego                  | małopolskie |
| MpKrakBujaka      | Kraków, ul. Bujaka                        | małopolskie |
| MpKrakBulwar      | Kraków, Bulwarowa                         | małopolskie |
| MpKrakOsPias      | Kraków, os. Piastów                       | małopolskie |
| MpKrakSwoszo      | Kraków, Swoszowice                        | małopolskie |
| MpKrakWadow       | Kraków, ul. Wadowicka                     | małopolskie |
| MpKrakZloRog      | Kraków, ul. Złoty Róg                     | małopolskie |
| MzWarAlNiepo      | Warszawa, al. Niepodległości              | mazowieckie |
| MzWarBajkowa      | Warszawa, ul. Bajkowa                     | mazowieckie |
| MzWarChrosci      | Warszawa, ul. Chrościckiego               | mazowieckie |
| MzWarKondrat      | Warszawa, ul. Kondratowicza               | mazowieckie |
| MzWarTolstoj      | Warszawa, ul. Tołstoja                    | mazowieckie |
| MzWarWokalna      | Warszawa, ul. Wokalna                     | mazowieckie |
| SlKatoKossut      | Katowice, ul. Kossutha                    | śląskie |
| SlKatoPlebA4      | Katowice, ul. Plebiscytowa / A4           | śląskie |
| SlGliwicMewy      | Gliwice, ul. Mewy                         | śląskie |
| SlCzestoArmK      | Częstochowa, Armii Krajowej               | śląskie |
| SlTychyTolst      | Tychy, ul. Tołstoja                       | śląskie |
| WpPoznDabrow      | Poznań, ul. Dąbrowskiego                  | wielkopolskie |
| WpPoznSzwajc      | Poznań, ul. Szwajcarska                   | wielkopolskie |
| WpPilaKusoci      | Piła, ul. Kusocińskiego                   | wielkopolskie |
| ZpSzczAndrze      | Szczecin, ul. Andrzejewskiego             | zachodniopomorskie |
| ZpSzczecPrze      | Szczecin, ul. Przestrzenna                | zachodnioporskie |
| ZpSzczPilsud      | Szczecin, ul. Piłsudskiego                | zachodniopomorskie |

## LISTA ZANIECZYSZCEŃ

| Zanieczyszczenie | Poziom szkodliwości | Dlaczego jest groźne | Główne skutki zdrowotne |
|------------------|--------------------|----------------------|--------------------------|
| PM2.5            | Bardzo wysoki      | Bardzo drobne cząstki – przenikają do krwi | Choroby serca, udary, nowotwory, skrócenie życia |
| Benzo(a)piren    | Bardzo wysoki      | Silnie rakotwórczy składnik smogu | Nowotwory (szczególnie płuc) |
| NO2              | Wysoki             | Drażni drogi oddechowe | Astma, zapalenie oskrzeli, pogorszenie funkcji płuc |
| PM10             | Wysoki             | Wnika do płuc (ale nie do krwi jak PM2.5) | Problemy oddechowe, kaszel, alergie |
| SO2              | Średnio-wysoki     | Silnie drażniący gaz | Skurcze oskrzeli, problemy z oddychaniem |
| O3 (ozon)        | Średnio-wysoki     | Silny utleniacz | Podrażnienia płuc, duszności, spadek wydolności |
| CO               | Wysoki (ostry)     | Blokuje transport tlenu we krwi | Zatrucia, zawroty głowy, śmierć w dużym stężeniu |
| NH3              | Średni             | Drażniący gaz | Podrażnienie oczu i dróg oddechowych |

| Zanieczyszczenie | Główne źródło (działalność człowieka) | Szczegóły |
|------------------|----------------------------------------|----------|
| PM2.5            | Ogrzewanie domów, transport, przemysł  | Spalanie węgla i drewna, spaliny, drobny pył wtórny |
| PM10             | Ogrzewanie domów, transport, przemysł  | Pył z pieców, ścieranie opon i hamulców, kurz |
| NO (tlenek azotu) | Transport, przemysł                   | Spalanie paliw w silnikach i instalacjach przemysłowych |
| NO2 (dwutlenek azotu) | Transport, przemysł              | Utlenianie NO, emisje z silników diesla |
| SO2 (dwutlenek siarki) | Przemysł, energetyka            | Spalanie węgla i paliw zawierających siarkę |
| CO (tlenek węgla) | Transport, ogrzewanie domów           | Niecałkowite spalanie paliw |
| NH3 (amoniak)     | Rolnictwo                             | Nawozy sztuczne, hodowla zwierząt |
| O3 (ozon troposferyczny) | Powstaje wtórnie (transport, przemysł) | Reakcje NOx i LZO pod wpływem słońca |
| Benzo(a)piren     | Ogrzewanie domów                      | Spalanie węgla i drewna, szczególnie w starych piecach |

### KODY ZANIECZYSZCZEŃ DLA DANYCH POCHODZACYCH

| Kod  | Zanieczyszczenie |
| ---- | ---------------- |
| 1    | SO₂              |
| 5    | PM10             |
| 8    | NO₂              |
| 7    | NO               |
| 6001 | PM2.5            |
| 10   | CO               |
| 9    | O₃               |

In [38]:
# # 1. Tab nr 5 - > PM10 (ul.PRZESTRZENNA, SZCZECIN, POLSKA)

# pm10_szn = pd.read_parquet('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/eko_projekt/SPO_PL0249A_5_001.parquet')

In [42]:
# # 2. TAB NR 2 ->  PM 2.5 (ul.PRZESTRZENNA, SZCZECIN, POLSKA)

# pm25_szn = pd.read_parquet('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/eko_projekt/SPO_PL0248A_6001_002.parquet')

# # pm25_szn.head()
# # pm25_szn.info()

In [84]:
# # 3. TAB  ->  PM10  (ul.PRZESTRZENNA, SZCZECIN, POLSKA)

# pm10_szn02= pd.read_parquet('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/eko_projekt/SPO_PL0248A_5_002.parquet')
# # display(pm10_szn02.head(2))
# display(pm10_szn.head(2))

Import Bibliotek

In [5]:
import pandas as pd 
import numpy as np
import os

## 2024 Dane z zanieczyszczeń PL ze strony GIOS.GOV.PL

#### PM 10

In [7]:
ds_pm10_2024 = pd.read_excel('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/data_air_pl_2024/2024_PM10_1g.xlsx')

In [8]:
ds_pm10_2024 = pd.read_excel('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/data_air_pl_2024/2024_PM10_1g.xlsx')
ds_pm10_2024.columns = ds_pm10_2024.iloc[0]

In [9]:
df_pm10_2024 = ds_pm10_2024.iloc[5:]

In [11]:
df_pm10_2024 = df_pm10_2024[['Kod stacji','LdLodzCzerni','LdLodzGdansk','WpPoznDabrow','WpPoznSzwajc']]
df_pm10_2024 = df_pm10_2024.rename(columns={'Kod stacji':'Date_time'})

In [19]:
print(df_pm10_2024.info())
print('\n','='*140,'\n')
display(df_pm10_2024.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 5 to 8788
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date_time     8784 non-null   object
 1   LdLodzCzerni  8285 non-null   object
 2   LdLodzGdansk  8588 non-null   object
 3   WpPoznDabrow  8533 non-null   object
 4   WpPoznSzwajc  8228 non-null   object
dtypes: object(5)
memory usage: 343.3+ KB
None

 ============================================================================================================================================

0            Date_time LdLodzCzerni LdLodzGdansk WpPoznDabrow WpPoznSzwajc
5  2024-01-01 01:00:00           48        138.9         41.5         72.3
6  2024-01-01 02:00:00           44        164.8         38.5         93.2

In [25]:
# EKSPORT DO PLIKU CSV.

# df_pm10_2024.to_csv('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/0_ready_raw_data/dane_pm10_ld_pz_2024.csv')

#### PM 2.5

In [27]:
ds_pm25_2024 = pd.read_excel('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/data_air_pl_2024/2024_PM25_1g.xlsx')
ds_pm25_2024.columns = ds_pm25_2024.iloc[0]
df_pm25_2024 = ds_pm25_2024.iloc[5:]
df_pm25_2024 = df_pm25_2024[['Kod stacji','LdLodzCzerni','WpPoznDabrow','WpPoznSzwajc']]
df_pm25_2024 = df_pm25_2024.rename(columns={'Kod stacji':'Date_time'})

In [29]:
print(df_pm25_2024.info())
print('\n','='*140,'\n')
display(df_pm25_2024.reset_index().head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 5 to 8788
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date_time     8784 non-null   object
 1   LdLodzCzerni  8264 non-null   object
 2   WpPoznDabrow  8533 non-null   object
 3   WpPoznSzwajc  8228 non-null   object
dtypes: object(4)
memory usage: 274.6+ KB
None

 ============================================================================================================================================

0  index            Date_time LdLodzCzerni WpPoznDabrow WpPoznSzwajc
0      5  2024-01-01 01:00:00         43.2         41.3         67.9
1      6  2024-01-01 02:00:00         39.2         38.4         88.7

In [31]:
# EKSPORT DO PLIKU CSV

# df_pm25_2024.to_csv('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/0_ready_raw_data/dane_pm25_ld_pz_2024.csv')

#### NO2

In [33]:
ds_no2_2024 = pd.read_excel('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/data_air_pl_2024/2024_NO2_1g.xlsx')
ds_no2_2024.columns = ds_no2_2024.iloc[0]
df_no2_2024 = ds_no2_2024.iloc[5:]
df_no2_2024 = df_no2_2024[['Kod stacji','LdLodzCzerni','LdLodzJanPaw','WpPoznDabrow','WpPoznSzwajc']]
df_no2_2024 = df_no2_2024.rename(columns={'Kod stacji':'Date_time'})

In [35]:
print(df_no2_2024.info())
print('\n','='*140,'\n')
print('DATA FRAME')
display(df_no2_2024.reset_index().head(2))
print('\n','='*140,'\n')
print('DATA_SET')
display(ds_no2_2024.reset_index().head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 5 to 8788
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date_time     8784 non-null   object
 1   LdLodzCzerni  8758 non-null   object
 2   LdLodzJanPaw  8749 non-null   object
 3   WpPoznDabrow  8469 non-null   object
 4   WpPoznSzwajc  8688 non-null   object
dtypes: object(5)
memory usage: 343.3+ KB
None

 ============================================================================================================================================

DATA FRAME

,index,Date_time,LdLodzCzerni,LdLodzJanPaw,WpPoznDabrow,WpPoznSzwajc
0,5,2024-01-01 01:00:00,10,25,27,15.8
1,6,2024-01-01 02:00:00,10.2,27,28,19.8

 ============================================================================================================================================

DATA_SET

,index,Kod stacji,LdLodzCzerni,LdLodzGdansk,LdLodzJanPaw,WpPoznDabrow,WpPoznSzwajc
0,0,Kod stacji,LdLodzCzerni,LdLodzGdansk,LdLodzJanPaw,WpPoznDabrow,WpPoznSzwajc
1,1,Wskaźnik,NO2,NO2,NO2,NO2,NO2

In [37]:
# EKSPORT DO PLIKU CSV

# df_no2_2024.to_csv('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/0_ready_raw_data/dane_no2_ld_pz_2024.csv')

#### CO -> Tlenek Węgla

In [39]:
ds_co_2024 = pd.read_excel('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/data_air_pl_2024/2024_CO_1g.xlsx')
ds_co_2024.columns = ds_co_2024.iloc[0]
df_co_2024 = ds_co_2024.iloc[5:]
df_co_2024 = df_co_2024[['Kod stacji','LdLodzJanPaw','WpPoznDabrow']]
df_co_2024 = df_co_2024.rename(columns={'Kod stacji':'Date_time'})

In [41]:
print(df_co_2024.info())
print('\n','='*140,'\n')
print('DATA FRAME')
display(df_co_2024.reset_index().head(2))
print('\n','='*140,'\n')
print('DATA_SET')
display(df_co_2024.reset_index().head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 5 to 8788
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date_time     8784 non-null   object
 1   LdLodzJanPaw  8759 non-null   object
 2   WpPoznDabrow  8654 non-null   object
dtypes: object(3)
memory usage: 206.0+ KB
None

 ============================================================================================================================================

DATA FRAME

0  index            Date_time LdLodzJanPaw WpPoznDabrow
0      5  2024-01-01 01:00:00        0.682        0.621
1      6  2024-01-01 02:00:00        0.783        0.668

 ============================================================================================================================================

DATA_SET

0  index  Kod stacji  LdLodzJanPaw  WpPoznDabrow
0      0  Kod stacji  LdLodzJanPaw  WpPoznDabrow
1      1    Wskaźnik            CO            CO

In [43]:
# EKSPORT DO PLIKU CSV

# df_co_2024.to_csv('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/0_ready_raw_data/dane_co_ld_pz_2024.csv')