In [7]:
# !pip install cdsapi
# !pip install eccodes
# !pip install cfgrib eccodes
# !conda install -c conda-forge eccodes cfgrib xarray -y

### Opis dataset

## IMPORT API - POGODA - POZNAŃ 2021

In [6]:
import cdsapi

dataset = "reanalysis-era5-single-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": [
            '10m_u_component_of_wind',
            '10m_v_component_of_wind',
            '2m_temperature',
            'boundary_layer_height',
            'surface_pressure',
            'total_cloud_cover'
    ],
    "year": ["2021"],
    "month": [
        "01","02","03","04","05","06","07","08","09","10","11","12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [52.54000, 16.80000, 52.28000, 17.06000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-05-11 17:08:52,403 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-05-11 17:08:52,404 INFO Request ID is b486813b-f552-4307-9b66-fe4e90e800f9
2026-05-11 17:08:52,553 INFO status has been updated to accepted
2026-05-11 17:09:04,375 INFO status has been updated to running
2026-05-11 17:17:19,809 INFO status has been updated to successful

b77b940d712521ff78ec60df93da268d.grib:   0%|          | 0.00/941k [00:00<?, ?B/s]

'b77b940d712521ff78ec60df93da268d.grib'

In [1]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
ds_pogoda_pz_2021 = xr.open_dataset(
    'b77b940d712521ff78ec60df93da268d.grib',
    engine='cfgrib'
)
import pandas as pd

df_pogoda_pz_2021 = ds_pogoda_pz_2021.to_dataframe().reset_index()


# Wyświetl wszystkie wiersze i kolumny
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# print(df_pogoda_pz_2021.shape)  # ile wierszy x kolumn
# df_pogoda_pz_2021.tail()


# EKSPORT DO PLIKU CSV.

df_pogoda_pz_2021.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/weather_pz_2021.csv')

## IMPORT API - POGODA - POZNAŃ 2022

In [7]:
import cdsapi

dataset = "reanalysis-era5-single-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": [
            '10m_u_component_of_wind',
            '10m_v_component_of_wind',
            '2m_temperature',
            'boundary_layer_height',
            'surface_pressure',
            'total_cloud_cover'
    ],
    "year": ["2022"],
    "month": [
        "01","02","03","04","05","06","07","08","09","10","11","12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [52.54000, 16.80000, 52.28000, 17.06000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-05-11 17:17:22,795 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-05-11 17:17:22,797 INFO Request ID is d077b3ca-aeb1-42af-8504-5c61612317e8
2026-05-11 17:17:25,108 INFO status has been updated to accepted
2026-05-11 17:25:51,352 INFO status has been updated to running
2026-05-11 17:33:52,731 INFO status has been updated to successful

4cddc9830db8c0c9e9d36b5365571f65.grib:   0%|          | 0.00/941k [00:00<?, ?B/s]

'4cddc9830db8c0c9e9d36b5365571f65.grib'

In [14]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
ds_pogoda_pz_2022 = xr.open_dataset(
    '4cddc9830db8c0c9e9d36b5365571f65.grib',
    engine='cfgrib'
)
import pandas as pd

df_pogoda_pz_2022 = ds_pogoda_pz_2022.to_dataframe().reset_index()


# Wyświetl wszystkie wiersze i kolumny
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# print(df_pogoda_pz_2022.shape)  # ile wierszy x kolumn
df_pogoda_pz_2022.tail()


# EKSPORT DO PLIKU CSV.

df_pogoda_pz_2022.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/weather_pz_2022.csv')

,time,latitude,longitude,number,step,surface,valid_time,u10,v10,t2m,blh,sp,tcc
1455,2022-12-30 18:00:00,52.5,17.0,0,0 days,0.0,2022-12-30 18:00:00,0.181198,4.785538,278.325928,340.957275,100390.8750,1.000000
1456,2022-12-31 00:00:00,52.5,17.0,0,0 days,0.0,2022-12-31 00:00:00,0.976776,5.734589,279.675537,579.549561,99962.7500,1.000000
1457,2022-12-31 06:00:00,52.5,17.0,0,0 days,0.0,2022-12-31 06:00:00,3.252731,4.473114,281.905762,516.145752,100025.6875,0.998993
1458,2022-12-31 12:00:00,52.5,17.0,0,0 days,0.0,2022-12-31 12:00:00,5.700546,4.471390,286.732910,1150.745605,99863.3750,1.000000
1459,2022-12-31 18:00:00,52.5,17.0,0,0 days,0.0,2022-12-31 18:00:00,5.587265,4.804504,288.235107,1127.552002,100120.9375,0.950012

In [16]:
df_pogoda_pz_2022.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/weather_pz_2022.csv')

## IMPORT API - POGODA - POZNAŃ 2023

In [2]:
import cdsapi

dataset = "reanalysis-era5-single-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": [
            '10m_u_component_of_wind',
            '10m_v_component_of_wind',
            '2m_temperature',
            'boundary_layer_height',
            'surface_pressure',
            'total_cloud_cover'
    ],
    "year": ["2023"],
    "month": [
        "01","02","03","04","05","06","07","08","09","10","11","12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [52.54000, 16.80000, 52.28000, 17.06000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-04-24 10:48:50,311 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-24 10:48:50,313 INFO Request ID is a9ed5deb-341b-4f0c-a02d-f73b72c5892e
2026-04-24 10:48:50,448 INFO status has been updated to accepted
2026-04-24 10:53:10,576 INFO status has been updated to running
2026-04-24 11:03:13,349 INFO status has been updated to successful

74ce8164492676df95d75faedb6d924c.grib:   0%|          | 0.00/941k [00:00<?, ?B/s]

'74ce8164492676df95d75faedb6d924c.grib'

In [7]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
ds_pogoda_pz_2023 = xr.open_dataset(
    '74ce8164492676df95d75faedb6d924c.grib',
    engine='cfgrib'
)

print(ds_pogoda_pz_2023)

<xarray.Dataset> Size: 58kB
Dimensions:     (time: 1460, latitude: 1, longitude: 1)
Coordinates:
  * time        (time) datetime64[ns] 12kB 2023-01-01 ... 2023-12-31T18:00:00
    valid_time  (time) datetime64[ns] 12kB ...
  * latitude    (latitude) float64 8B 52.5
  * longitude   (longitude) float64 8B 17.0
    number      int64 8B ...
    step        timedelta64[ns] 8B ...
    surface     float64 8B ...
Data variables:
    u10         (time, latitude, longitude) float32 6kB ...
    v10         (time, latitude, longitude) float32 6kB ...
    t2m         (time, latitude, longitude) float32 6kB ...
    blh         (time, latitude, longitude) float32 6kB ...
    sp          (time, latitude, longitude) float32 6kB ...
    tcc         (time, latitude, longitude) float32 6kB ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-24T15:23 GRIB to CDM+CF via cfgrib-0.9.1...

In [8]:
import pandas as pd

df_pogoda_pz_2023 = ds_pogoda_pz_2023.to_dataframe().reset_index()


# Wyświetl wszystkie wiersze i kolumny
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print(df_pogoda_pz_2023.shape)  # ile wierszy x kolumn
df_pogoda_pz_2023.tail()

(1460, 13)

,time,latitude,longitude,number,step,surface,valid_time,u10,v10,t2m,blh,sp,tcc
1455,2023-12-30 18:00:00,52.5,17.0,0,0 days,0.0,2023-12-30 18:00:00,4.639160,0.612579,277.640869,806.484131,100270.5000,0.556244
1456,2023-12-31 00:00:00,52.5,17.0,0,0 days,0.0,2023-12-31 00:00:00,1.529984,1.296890,274.563721,83.082397,100385.1875,0.971832
1457,2023-12-31 06:00:00,52.5,17.0,0,0 days,0.0,2023-12-31 06:00:00,-1.036987,2.553833,273.863037,112.155014,100267.8125,0.939301
1458,2023-12-31 12:00:00,52.5,17.0,0,0 days,0.0,2023-12-31 12:00:00,-2.960464,1.773254,278.915283,309.695068,99972.3125,1.000000
1459,2023-12-31 18:00:00,52.5,17.0,0,0 days,0.0,2023-12-31 18:00:00,-2.962860,2.485657,277.594482,266.371338,99636.8750,1.000000

In [11]:
# EKSPORT DO PLIKU CSV.

# df_pogoda_pz_2023.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/weather_pz_2023.csv')

<hr style="height:6px;border:none;background-color:black;">

## IMPORT API - POGODA - POZNAŃ 2024

In [5]:
import cdsapi

dataset = "reanalysis-era5-single-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": [
            '10m_u_component_of_wind',
            '10m_v_component_of_wind',
            '2m_temperature',
            'boundary_layer_height',
            'surface_pressure',
            'total_cloud_cover'
    ],
    "year": ["2024"],
    "month": [
        "01","02","03","04","05","06","07","08","09","10","11","12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [52.54000, 16.80000, 52.28000, 17.06000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-04-09 18:16:40,792 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-09 18:16:40,801 INFO Request ID is 9557e2fb-7042-4624-ab4c-af9a3efba9cc
2026-04-09 18:16:40,982 INFO status has been updated to accepted
2026-04-09 18:16:55,003 INFO status has been updated to running
2026-04-09 18:29:03,724 INFO status has been updated to successful

4be675791c743e28430282a47dd2d421.grib:   0%|          | 0.00/944k [00:00<?, ?B/s]

'4be675791c743e28430282a47dd2d421.grib'

In [17]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
ds_pogoda_pz_2024 = xr.open_dataset(
    '4be675791c743e28430282a47dd2d421.grib',
    engine='cfgrib'
)

print(ds_pogoda_pz_2024)

<xarray.Dataset> Size: 59kB
Dimensions:     (time: 1464, latitude: 1, longitude: 1)
Coordinates:
  * time        (time) datetime64[ns] 12kB 2004-01-01 ... 2004-12-31T18:00:00
    valid_time  (time) datetime64[ns] 12kB ...
  * latitude    (latitude) float64 8B 52.5
  * longitude   (longitude) float64 8B 17.0
    number      int64 8B ...
    step        timedelta64[ns] 8B ...
    surface     float64 8B ...
Data variables:
    u10         (time, latitude, longitude) float32 6kB ...
    v10         (time, latitude, longitude) float32 6kB ...
    t2m         (time, latitude, longitude) float32 6kB ...
    blh         (time, latitude, longitude) float32 6kB ...
    sp          (time, latitude, longitude) float32 6kB ...
    tcc         (time, latitude, longitude) float32 6kB ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-04-09T18:36 GRIB to CDM+CF via cfgrib-0.9.1...

In [19]:
import pandas as pd

df_pogoda_pz_2024 = ds_pogoda_pz_2024.to_dataframe().reset_index()


# Wyświetl wszystkie wiersze i kolumny
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print(df_pogoda_pz_2024.shape)  # ile wierszy x kolumn
df_pogoda_pz_2024.head()

(1464, 13)

,time,latitude,longitude,number,step,surface,valid_time,u10,v10,t2m,blh,sp,tcc
0,2004-01-01 00:00:00,52.5,17.0,0,0 days,0.0,2004-01-01 00:00:00,1.568558,-2.186691,273.004395,243.424942,101123.0000,0.840271
1,2004-01-01 06:00:00,52.5,17.0,0,0 days,0.0,2004-01-01 06:00:00,0.818604,-2.192627,270.626709,279.722656,100916.0625,0.781372
2,2004-01-01 12:00:00,52.5,17.0,0,0 days,0.0,2004-01-01 12:00:00,-1.264282,-2.593384,272.322021,688.956543,100660.3125,0.889282
3,2004-01-01 18:00:00,52.5,17.0,0,0 days,0.0,2004-01-01 18:00:00,0.084534,-3.385330,270.798340,492.097168,100484.3125,0.599670
4,2004-01-02 00:00:00,52.5,17.0,0,0 days,0.0,2004-01-02 00:00:00,1.166565,-2.747696,270.697266,828.987305,100383.0000,0.926147

<hr style="height:6px;border:none;background-color:black;">

## IMPORT API - POGODA - ŁÓDŹ 2023

In [4]:
import cdsapi

dataset = "reanalysis-era5-single-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": [
            '10m_u_component_of_wind',
            '10m_v_component_of_wind',
            '2m_temperature',
            'boundary_layer_height',
            'surface_pressure',
            'total_cloud_cover'
    ],
    "year": ["2023"],
    "month": [
        "01","02","03","04","05","06","07","08","09","10","11","12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [51.91000, 19.33000, 51.64000, 19.59000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-04-24 11:03:16,615 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-24 11:03:16,618 INFO Request ID is 1ce78f46-73e6-41ca-9c5f-16e7ed2456d6
2026-04-24 11:03:16,749 INFO status has been updated to accepted
2026-04-24 11:13:39,224 INFO status has been updated to running
2026-04-24 11:21:41,079 INFO status has been updated to successful

d1ce8dfd792af6603a2246a39f106ed8.grib:   0%|          | 0.00/941k [00:00<?, ?B/s]

'd1ce8dfd792af6603a2246a39f106ed8.grib'

In [14]:
import eccodes
import xarray as xr
import cfgrib
import pandas as pd

# Odczyt pliku GRIB przez xarray
ds_pogoda_ld_2023 = xr.open_dataset(
    'd1ce8dfd792af6603a2246a39f106ed8.grib',
    engine='cfgrib'
)


df_pogoda_ld_2023 = ds_pogoda_ld_2023.to_dataframe().reset_index()


# Wyświetl wszystkie wiersze i kolumny
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print(df_pogoda_ld_2023.shape)  # ile wierszy x kolumn
df_pogoda_ld_2023.head()

(1460, 13)

,time,latitude,longitude,number,step,surface,valid_time,u10,v10,t2m,blh,sp,tcc
0,2023-01-01 00:00:00,51.75,19.5,0,0 days,0.0,2023-01-01 00:00:00,5.353333,4.853073,285.840088,647.280762,99286.1250,0.787537
1,2023-01-01 06:00:00,51.75,19.5,0,0 days,0.0,2023-01-01 06:00:00,6.153107,3.718613,286.227051,745.224365,99435.4375,0.596741
2,2023-01-01 12:00:00,51.75,19.5,0,0 days,0.0,2023-01-01 12:00:00,5.434402,3.866943,289.677979,815.427246,99555.2500,0.809631
3,2023-01-01 18:00:00,51.75,19.5,0,0 days,0.0,2023-01-01 18:00:00,3.296982,3.080399,284.966064,291.857910,99843.5000,0.985565
4,2023-01-02 00:00:00,51.75,19.5,0,0 days,0.0,2023-01-02 00:00:00,2.058640,3.253723,281.799561,184.288116,99938.3125,0.989990

In [16]:
# EKSPORT DO PLIKU CSV.

# df_pogoda_ld_2023.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/weather_ld_2023.csv')

<hr style="height:6px;border:none;background-color:black;">

## IMPORT API - POGODA - ŁÓDŹ 2024

In [28]:
import cdsapi

dataset = "reanalysis-era5-single-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": [
            '10m_u_component_of_wind',
            '10m_v_component_of_wind',
            '2m_temperature',
            'boundary_layer_height',
            'surface_pressure',
            'total_cloud_cover'
    ],
    "year": ["2024"],
    "month": [
        "01","02","03","04","05","06","07","08","09","10","11","12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [51.91000, 19.33000, 51.64000, 19.59000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-04-09 18:50:50,506 INFO [2025-12-11T00:00:00] Please note that a dedicated catalogue entry for this dataset, post-processed and stored in Analysis Ready Cloud Optimized (ARCO) format (Zarr), is available for optimised time-series retrievals (i.e. for retrieving data from selected variables for a single point over an extended period of time in an efficient way). You can discover it [here](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels-timeseries?tab=overview)
2026-04-09 18:50:50,507 INFO Request ID is 8fb6baff-abdb-4ce2-a240-cb32d3a2b562
2026-04-09 18:50:50,637 INFO status has been updated to accepted
2026-04-09 18:55:11,055 INFO status has been updated to running
2026-04-09 19:03:12,810 INFO status has been updated to successful

13ba94c297cd01e420b8c6cd00fa270a.grib:   0%|          | 0.00/944k [00:00<?, ?B/s]

'13ba94c297cd01e420b8c6cd00fa270a.grib'

In [3]:
import eccodes
import xarray as xr
import cfgrib
import pandas as pd

# Odczyt pliku GRIB przez xarray
ds_pogoda_ld_2024 = xr.open_dataset(
    '13ba94c297cd01e420b8c6cd00fa270a.grib',
    engine='cfgrib'
)


df_pogoda_ld_2024 = ds_pogoda_ld_2024.to_dataframe().reset_index()


# Wyświetl wszystkie wiersze i kolumny
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print(df_pogoda_ld_2024.shape)  # ile wierszy x kolumn
df_pogoda_ld_2024.head()

(1464, 13)

,time,latitude,longitude,number,step,surface,valid_time,u10,v10,t2m,blh,sp,tcc
0,2024-01-01 00:00:00,51.75,19.5,0,0 days,0.0,2024-01-01 00:00:00,-0.215057,1.911789,276.628174,94.372345,98493.5625,1.000000
1,2024-01-01 06:00:00,51.75,19.5,0,0 days,0.0,2024-01-01 06:00:00,1.433395,0.123932,276.127686,104.462128,98374.7500,1.000000
2,2024-01-01 12:00:00,51.75,19.5,0,0 days,0.0,2024-01-01 12:00:00,3.615005,0.483673,277.357178,498.559082,98336.8125,1.000000
3,2024-01-01 18:00:00,51.75,19.5,0,0 days,0.0,2024-01-01 18:00:00,4.449921,0.167877,277.015137,557.305908,98451.3125,0.885254
4,2024-01-02 00:00:00,51.75,19.5,0,0 days,0.0,2024-01-02 00:00:00,4.027206,1.119080,276.745117,400.038818,98538.0625,1.000000

In [11]:
# EKSPORT DO PLIKU CSV. 

# df_pogoda_ld_2024.to_csv('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/qualityair_projekt/0_ready_raw_data/weather_ld_2024.csv')
#

In [13]:
df_pogoda_ld_2024.loc[df_pogoda_ld_2024['time']=='2024-01-01 18:00:00']

,time,latitude,longitude,number,step,surface,valid_time,u10,v10,t2m,blh,sp,tcc
3,2024-01-01 18:00:00,51.75,19.5,0,0 days,0.0,2024-01-01 18:00:00,4.449921,0.167877,277.015137,557.305908,98451.3125,0.885254