In [11]:
import pandas as pd
import os

### W tym Notebooku dokonano zaczytania danych dotyczcych jakości powietrza.
### z archiwum Głównego Inspektoratu Ochrony Środowiska.
Zastosowano następujace kroki:
- Zaczytanie danych z pliku źródłowego dla wybranych zanieczyszczeń 
- Wybrano badane stacje pomiarowe w wybranych miastach
- utworzono Data Frame dla wybranych kolunm oraz odpowienio opisano kolumny.
- Eksport jako Raw_data do plików .csv 


źródło : https://powietrze.gios.gov.pl/pjp/archives

## LISTA STACJI PL WG KODU

| Kod stacji            | Miasto                |
|----------------------|----------------------|
| DsChojnowMalMOB      | Chojnów              |
| DsJelGorOgin         | Jelenia Góra         |
| DsKlodzSzkol         | Kłodzko              |
| DsKudowaSzkoMOB      | Kudowa-Zdrój         |
| DsWrocAlWisn         | Wrocław              |
| DsWrocWybCon         | Wrocław              |
| KpBydPlPozna         | Bydgoszcz            |
| KpBydWarszaw         | Bydgoszcz            |
| KpNaklWawrzy         | Nakło nad Notecią    |
| KpSwiecJPawlMOB      | Świecie              |
| KpToruKaszow         | Toruń                |
| KpWloclOkrze         | Włocławek            |
| LbLubObywate         | Lublin               |
| LbLukBulNiepMOB      | Łuków                |
| LbZamoHrubie         | Zamość               |
| LdKutn1Maja7MOB      | Kutno                |
| LdLaskNarutoMOB      | Łask                 |
| LdLodzCzerni         | Łódź                 |
| LdRadomsRoln         | Radomsko             |
| LdZgieMielcz         | Zgierz               |
| LuGorzKosGdy         | Gorzów Wielkopolski  |
| LuLubsStrzelMOB      | Lubsko               |
| LuWsKaziWiel         | Wschowa              |
| LuZarySzyman         | Żary                 |
| LuZielKrotka         | Zielona Góra         |
| MpKrakAlKras         | Kraków               |
| MpKrakBulwar         | Kraków               |
| MpTarRoSitko         | Tarnów               |
| MzBialaKmiciMOB      | Biała Podlaska       |
| MzKonJezZero         | Konstancin-Jeziorna  |
| MzLegZegrzyn         | Legionowo            |
| MzOtwoBrzozo         | Otwock               |
| MzPiasPulask         | Piaseczno            |
| MzPlocMiReja         | Płock                |
| MzPultuskMicMOB      | Pułtusk              |
| MzRadTochter         | Radom                |
| MzSiedKonars         | Siedlce              |
| MzWarAlNiepo         | Warszawa             |
| MzWarBajkowa         | Warszawa             |
| MzWarChrosci         | Warszawa             |
| MzWarKondrat         | Warszawa             |
| MzWarTolstoj         | Warszawa             |
| MzWarWokalna         | Warszawa             |
| MzZyraRoosev         | Żyrardów             |
| OpKKozBSmial         | Kędzierzyn-Koźle     |
| OpOpoleKoszy         | Opole                |
| OpStrzOpWyszMOB      | Strzelce Opolskie    |
| PdAugustowUz         | Augustów             |
| PdBialAlPils         | Białystok            |
| PdBialPPiech         | Białystok            |
| PdBialUpalna         | Białystok            |
| PdBorsukowiz         | Borsukowizna         |
| PdGrajewoWPoMOB      | Grajewo              |
| PdSuwPulask2         | Suwałki              |
| PkBoguchAngeMOB      | Boguchwała           |
| PkDebiGrottg         | Dębica               |
| PkJarosPruch         | Jarosław             |
| PkJasloSikor         | Jasło                |
| PkKrosKletow         | Krosno               |
| PkMielBierna         | Mielec               |
| PkNiskoSzkla         | Nisko                |
| PkPrzemGrunw         | Przemyśl             |
| PkRymZdrPark         | Rymanów-Zdrój        |
| PkRzeszPilsu         | Rzeszów              |
| PkRzeszSloci         | Rzeszów              |
| PkRzeszStarz         | Rzeszów              |
| PmBytowMila1MOB      | Bytów                |
| PmGdaLeczkow         | Gdańsk               |
| PmGdaWyzwole         | Gdańsk               |
| PmGdyPorebsk         | Gdynia               |
| PmKosTargowa         | Kościerzyna          |
| PmSopBiPlowc         | Sopot                |
| SkLagowZaploMOB      | Łagów                |
| SkPolaRuszcz         | Połaniec             |
| SkSkarz1MajaMOB      | Skarżysko-Kamienna   |
| SkStaraZlota         | Starachowice         |
| SlBielPartyz         | Bielsko-Biała        |
| SlGoczaUzdroMOB      | Goczałkowice-Zdrój   |
| SlJastrZdroj         | Jastrzębie-Zdrój     |
| SlKatoKossut         | Katowice             |
| SlKatoPlebA4         | Katowice             |
| SlRaciborzWPMOB      | Racibórz             |
| SlZlotPotLes         | Złoty Potok          |
| SlZywieKoper         | Żywiec               |
| WmDzialPolnaMOB      | Działdowo            |
| WmElbBazynsk         | Elbląg               |
| WmElkStadion         | Ełk                  |
| WmOlsPuszkin         | Olsztyn              |
| WpKaliSawick         | Kalisz               |
| WpKoscianMayMOB      | Kościan              |
| WpPoznDabrow         | Poznań               |
| WpPoznSzwajc         | Poznań               |
| ZpDabkiSztorMOB      | Dąbki                |
| ZpKolZolkiew         | Kołobrzeg            |
| ZpSzczAndrze         | Szczecin             |
| ZpSzczPilsud         | Szczecin             |

| Kod stacji        | Lokalizacja (miasto + przybliżone miejsce) | Województwo |
|-------------------|-------------------------------------------|-------------|
| DsChojnowMalMOB   | Chojnów (mobilna)                         | dolnośląskie |
| DsCzerStraza      | Czerna / Straża                           | dolnośląskie |
| DsDziePilsud      | Dzierżoniów, ul. Piłsudskiego             | dolnośląskie |
| DsJelGorOgin      | Jelenia Góra, ul. Ogińskiego              | dolnośląskie |
| DsKlodzSzkol      | Kłodzko, okolice szkoły                   | dolnośląskie |
| DsKudowaSzkoMOB   | Kudowa-Zdrój (mobilna)                    | dolnośląskie |
| DsLegAlRzecz      | Legnica, al. Rzeczypospolitej             | dolnośląskie |
| DsNowRudJezi      | Nowa Ruda, ul. Jeziorna                   | dolnośląskie |
| DsOlawZolnAK      | Oława, ul. Żołnierzy AK                   | dolnośląskie |
| DsStrzegomMOB     | Strzegom (mobilna)                        | dolnośląskie |
| DsTrzebniMaj      | Trzebnica, ul. 3 Maja                     | dolnośląskie |
| DsWalbrzWyso      | Wałbrzych, ul. Wysockiego                 | dolnośląskie |
| DsWrocWybCon      | Wrocław, ul. Wyb. Conrada-Korzeniowskiego | dolnośląskie |
| KpBydPlPozna      | Bydgoszcz, pl. Poznański                  | kujawsko-pomorskie |
| KpBydWarszaw      | Bydgoszcz, ul. Warszawska                 | kujawsko-pomorskie |
| KpGrudPilsud      | Grudziądz, ul. Piłsudskiego               | kujawsko-pomorskie |
| KpInowSolank      | Inowrocław, Solanki                       | kujawsko-pomorskie |
| KpNaklWawrzy      | Nakło nad Notecią, ul. Wawrzyniaka        | kujawsko-pomorskie |
| KpSwiecJPawlMOB   | Świecie (mobilna)                         | kujawsko-pomorskie |
| KpToruDziewu      | Toruń, ul. Dziewulskiego                  | kujawsko-pomorskie |
| KpToruKaszow      | Toruń, ul. Kaszownika                     | kujawsko-pomorskie |
| KpToruWSikor      | Toruń, ul. W. Sikorskiego                 | kujawsko-pomorskie |
| KpWloclKalis      | Włocławek, ul. Kaliska                    | kujawsko-pomorskie |
| KpWloclOkrze      | Włocławek, ul. Okrzei                     | kujawsko-pomorskie |
| MpKrakAlKras      | Kraków, al. Krasińskiego                  | małopolskie |
| MpKrakBujaka      | Kraków, ul. Bujaka                        | małopolskie |
| MpKrakBulwar      | Kraków, Bulwarowa                         | małopolskie |
| MpKrakOsPias      | Kraków, os. Piastów                       | małopolskie |
| MpKrakSwoszo      | Kraków, Swoszowice                        | małopolskie |
| MpKrakWadow       | Kraków, ul. Wadowicka                     | małopolskie |
| MpKrakZloRog      | Kraków, ul. Złoty Róg                     | małopolskie |
| MzWarAlNiepo      | Warszawa, al. Niepodległości              | mazowieckie |
| MzWarBajkowa      | Warszawa, ul. Bajkowa                     | mazowieckie |
| MzWarChrosci      | Warszawa, ul. Chrościckiego               | mazowieckie |
| MzWarKondrat      | Warszawa, ul. Kondratowicza               | mazowieckie |
| MzWarTolstoj      | Warszawa, ul. Tołstoja                    | mazowieckie |
| MzWarWokalna      | Warszawa, ul. Wokalna                     | mazowieckie |
| SlKatoKossut      | Katowice, ul. Kossutha                    | śląskie |
| SlKatoPlebA4      | Katowice, ul. Plebiscytowa / A4           | śląskie |
| SlGliwicMewy      | Gliwice, ul. Mewy                         | śląskie |
| SlCzestoArmK      | Częstochowa, Armii Krajowej               | śląskie |
| SlTychyTolst      | Tychy, ul. Tołstoja                       | śląskie |
| WpPoznDabrow      | Poznań, ul. Dąbrowskiego                  | wielkopolskie |
| WpPoznSzwajc      | Poznań, ul. Szwajcarska                   | wielkopolskie |
| WpPilaKusoci      | Piła, ul. Kusocińskiego                   | wielkopolskie |
| ZpSzczAndrze      | Szczecin, ul. Andrzejewskiego             | zachodniopomorskie |
| ZpSzczecPrze      | Szczecin, ul. Przestrzenna                | zachodnioporskie |
| ZpSzczPilsud      | Szczecin, ul. Piłsudskiego                | zachodniopomorskie |

## LISTA ZANIECZYSZCEŃ

| Zanieczyszczenie | Poziom szkodliwości | Dlaczego jest groźne | Główne skutki zdrowotne |
|------------------|--------------------|----------------------|--------------------------|
| PM2.5            | Bardzo wysoki      | Bardzo drobne cząstki – przenikają do krwi | Choroby serca, udary, nowotwory, skrócenie życia |
| Benzo(a)piren    | Bardzo wysoki      | Silnie rakotwórczy składnik smogu | Nowotwory (szczególnie płuc) |
| NO2              | Wysoki             | Drażni drogi oddechowe | Astma, zapalenie oskrzeli, pogorszenie funkcji płuc |
| PM10             | Wysoki             | Wnika do płuc (ale nie do krwi jak PM2.5) | Problemy oddechowe, kaszel, alergie |
| SO2              | Średnio-wysoki     | Silnie drażniący gaz | Skurcze oskrzeli, problemy z oddychaniem |
| O3 (ozon)        | Średnio-wysoki     | Silny utleniacz | Podrażnienia płuc, duszności, spadek wydolności |
| CO               | Wysoki (ostry)     | Blokuje transport tlenu we krwi | Zatrucia, zawroty głowy, śmierć w dużym stężeniu |
| NH3              | Średni             | Drażniący gaz | Podrażnienie oczu i dróg oddechowych |

| Zanieczyszczenie | Główne źródło (działalność człowieka) | Szczegóły |
|------------------|----------------------------------------|----------|
| PM2.5            | Ogrzewanie domów, transport, przemysł  | Spalanie węgla i drewna, spaliny, drobny pył wtórny |
| PM10             | Ogrzewanie domów, transport, przemysł  | Pył z pieców, ścieranie opon i hamulców, kurz |
| NO (tlenek azotu) | Transport, przemysł                   | Spalanie paliw w silnikach i instalacjach przemysłowych |
| NO2 (dwutlenek azotu) | Transport, przemysł              | Utlenianie NO, emisje z silników diesla |
| SO2 (dwutlenek siarki) | Przemysł, energetyka            | Spalanie węgla i paliw zawierających siarkę |
| CO (tlenek węgla) | Transport, ogrzewanie domów           | Niecałkowite spalanie paliw |
| NH3 (amoniak)     | Rolnictwo                             | Nawozy sztuczne, hodowla zwierząt |
| O3 (ozon troposferyczny) | Powstaje wtórnie (transport, przemysł) | Reakcje NOx i LZO pod wpływem słońca |
| Benzo(a)piren     | Ogrzewanie domów                      | Spalanie węgla i drewna, szczególnie w starych piecach |

### KODY ZANIECZYSZCZEŃ DLA DANYCH POCHODZACYCH

| Kod  | Zanieczyszczenie |
| ---- | ---------------- |
| 1    | SO₂              |
| 5    | PM10             |
| 8    | NO₂              |
| 7    | NO               |
| 6001 | PM2.5            |
| 10   | CO               |
| 9    | O₃               |

In [21]:
# # 1. Tab nr 5 - > PM10 (ul.PRZESTRZENNA, SZCZECIN, POLSKA)

# pm10_szn = pd.read_parquet('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/eko_projekt/SPO_PL0249A_5_001.parquet')

In [22]:
# # 2. TAB NR 2 ->  PM 2.5 (ul.PRZESTRZENNA, SZCZECIN, POLSKA)

# pm25_szn = pd.read_parquet('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/eko_projekt/SPO_PL0248A_6001_002.parquet')

# # pm25_szn.head()
# # pm25_szn.info()

In [23]:
# # 3. TAB  ->  PM10  (ul.PRZESTRZENNA, SZCZECIN, POLSKA)

# pm10_szn02= pd.read_parquet('/Users/marcinurbanski/Desktop/merito_projekt_pliki_robocze/eko_projekt/SPO_PL0248A_5_002.parquet')
# # display(pm10_szn02.head(2))
# display(pm10_szn.head(2))

Import Bibliotek

In [25]:
import pandas as pd 
import numpy as np
import os

# 2023 Dane z zanieczyszczeń PL ze strony GIOS.GOV.PL

In [27]:
ds_pm10_2023 = pd.read_excel('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/data_air_pl_2023/2023_PM10_1g.xlsx')
ds_pm25_2023 = pd.read_excel('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/data_air_pl_2023/2023_PM25_1g.xlsx')
ds_no2_2023 = pd.read_excel('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/data_air_pl_2023/2023_NO2_1g.xlsx')
ds_co_2023 = pd.read_excel('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/data_air_pl_2023/2023_CO_1g.xlsx')

#### Tworzenie DataFrame dla danych PM10 2023

In [29]:
ds_pm10_2023.columns = ds_pm10_2023.iloc[0]
df_pm10_2023 = ds_pm10_2023.iloc[5:]
df_pm10_2023 = df_pm10_2023[['Kod stacji','LdLodzCzerni','WpPoznSzwajc']]
df_pm10_2023 = df_pm10_2023.rename(columns={'Kod stacji':'Date_time',
                                            'LdLodzCzerni':'LdLodzCzerni_PM10',
                                            'WpPoznSzwajc':'WpPoznSzwajc_PM10'})
df_pm10_2023['Date_time'] = pd.to_datetime(df_pm10_2023['Date_time'])

print(df_pm10_2023.info())
print('\n','='*140,'\n')
display(ds_pm10_2023.head())
display(df_pm10_2023.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 5 to 8764
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date_time          8760 non-null   datetime64[ns]
 1   LdLodzCzerni_PM10  8610 non-null   object
 2   WpPoznSzwajc_PM10  8730 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 205.4+ KB
None

 ============================================================================================================================================

,Kod stacji,LdLodzCzerni,LdLodzGdansk,LdLodzJanPaw,WpPoznDabrow,WpPoznSzwajc
0,Kod stacji,LdLodzCzerni,LdLodzGdansk,LdLodzJanPaw,WpPoznDabrow,WpPoznSzwajc
1,Wskaźnik,PM10,PM10,PM10,PM10,PM10
2,Czas uśredniania,1g,1g,1g,1g,1g
3,Jednostka,ug/m3,ug/m3,ug/m3,ug/m3,ug/m3
4,Kod stanowiska,LdLodzCzerni-PM10-1g,LdLodzGdansk-PM10-1g,LdLodzJanPaw-PM10-1g,WpPoznDabrow-PM10-1g,WpPoznSzwajc-PM10-1g

0           Date_time LdLodzCzerni_PM10 WpPoznSzwajc_PM10
5 2023-01-01 01:00:00                25           9.87387
6 2023-01-01 02:00:00                 7           14.9775

#### Tworzenie DataFrame dla danych PM25 2023

In [31]:
ds_pm25_2023.columns = ds_pm25_2023.iloc[0]
df_pm25_2023 = ds_pm25_2023.iloc[5:]
df_pm25_2023 = df_pm25_2023[['Kod stacji','LdLodzCzerni','WpPoznSzwajc']]
df_pm25_2023 = df_pm25_2023.rename(columns={'Kod stacji':'Date_time',
                                           'LdLodzCzerni':'LdLodzCzerni_PM25',
                                            'WpPoznSzwajc':'WpPoznSzwajc_PM25'})
df_pm25_2023['Date_time'] = pd.to_datetime(df_pm25_2023['Date_time'])

print(df_pm25_2023.info())
print('\n','='*140,'\n')
display(ds_pm25_2023.iloc[5:7])
display(df_pm25_2023.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 5 to 8764
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date_time          8760 non-null   datetime64[ns]
 1   LdLodzCzerni_PM25  8591 non-null   object
 2   WpPoznSzwajc_PM25  8730 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 205.4+ KB
None

 ============================================================================================================================================

0           Kod stacji LdLodzCzerni WpPoznDabrow WpPoznSzwajc ZpSzczPilsud
5  2023-01-01 01:00:00       21.384      27.3942      8.16218      31.3938
6  2023-01-01 02:00:00       6.4152      7.81944      12.9847      10.2534

0           Date_time LdLodzCzerni_PM25 WpPoznSzwajc_PM25
5 2023-01-01 01:00:00            21.384           8.16218
6 2023-01-01 02:00:00            6.4152           12.9847

#### Tworzenie DataFrame dla danych NO2 2023

In [33]:
ds_no2_2023.columns = ds_no2_2023.iloc[0]
df_no2_2023 = ds_no2_2023.iloc[6:]
df_no2_2023 = df_no2_2023[['Kod stacji','LdLodzCzerni','WpPoznSzwajc']]
df_no2_2023 = df_no2_2023.rename(columns={'Kod stacji':'Date_time',
                                          'LdLodzCzerni':'LdLodzCzerni_NO2',
                                          'WpPoznSzwajc':'WpPoznSzwajc_NO2'})
df_no2_2023['Date_time'] = pd.to_datetime(df_no2_2023['Date_time'])
print(df_no2_2023.info())
print('\n','='*140,'\n')
display(ds_no2_2023.iloc[6:8])
display(df_no2_2023.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 6 to 8765
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date_time         8760 non-null   datetime64[ns]
 1   LdLodzCzerni_NO2  8691 non-null   object
 2   WpPoznSzwajc_NO2  8062 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 205.4+ KB
None

 ============================================================================================================================================

,Kod stacji,LdLodzCzerni,LdLodzGdansk,LdLodzJanPaw,WpPoznDabrow,WpPoznSzwajc
6,2023-01-01 01:00:00,7.9,9.9,5.4,23.3678,4.27716
7,2023-01-01 02:00:00,3.8,11.3,9.5,21.331,5.02854

0           Date_time LdLodzCzerni_NO2 WpPoznSzwajc_NO2
6 2023-01-01 01:00:00              7.9          4.27716
7 2023-01-01 02:00:00              3.8          5.02854

#### Tworzenie DataFrame dla danych CO 2023

In [35]:
# UWAGA: Dla pomiarów CO w Poznaniu w 2024 nie ma danych ze stacji WpPoznSzwajc[2024] tylko sa ze stacji WpPoznDobrow[2023]
#        Dla usprawnienia daslszych agregacji  zapisujemy nazwę stacji w formie uproszczonej WpPozn_CO (bez rozróżnienia
#        która stacja odpowiada za pomiar CO w latach 2023 i 2024)

ds_co_2023.columns = ds_co_2023.iloc[0]
df_co_2023 = ds_co_2023.iloc[5:]
df_co_2023 = df_co_2023[['Kod stacji','LdLodzJanPaw','WpPoznSzwajc']]
df_co_2023 = df_co_2023.rename(columns={'Kod stacji':'Date_time',
                                        'LdLodzJanPaw':'LdLodzJanPaw_CO',
                                        'WpPoznSzwajc':'WpPozn_CO'})
df_co_2023['Date_time'] = pd.to_datetime(df_co_2023['Date_time'])
print(df_co_2023.info())
print('\n','='*140,'\n')
display(ds_co_2023.iloc[5:7])
display(df_co_2023.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 5 to 8764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date_time        8760 non-null   datetime64[ns]
 1   LdLodzJanPaw_CO  8723 non-null   object
 2   WpPozn_CO        8665 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 205.4+ KB
None

 ============================================================================================================================================

0           Kod stacji LdLodzJanPaw WpPoznDabrow WpPoznSzwajc
5  2023-01-01 01:00:00        0.394      0.23496      0.32176
6  2023-01-01 02:00:00         0.43      0.22526      0.32205

0           Date_time LdLodzJanPaw_CO WpPozn_CO
5 2023-01-01 01:00:00           0.394   0.32176
6 2023-01-01 02:00:00            0.43   0.32205

#### Merge Wszyskich DataSetów 2023 + Eksport do cvs

In [37]:
from functools import reduce

dfs_list = [df_pm10_2023, df_pm25_2023, df_no2_2023, df_co_2023]

df_polution_2023_merged = reduce(lambda left, right: left.merge(right, on="Date_time", how="left"), dfs_list)

# Eksport do pliku w raw data
df_polution_2023_merged.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/data_polution_2023')

# 2024 Dane z zanieczyszczeń PL ze strony GIOS.GOV.PL

In [39]:
import pandas as pd
ds_pm10_2024 = pd.read_excel('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/data_air_pl_2024/2024_PM10_1g.xlsx')
ds_pm25_2024 = pd.read_excel('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/data_air_pl_2024/2024_PM25_1g.xlsx')
ds_no2_2024 = pd.read_excel('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/data_air_pl_2024/2024_NO2_1g.xlsx')
ds_co_2024 = pd.read_excel('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/data_air_pl_2024/2024_CO_1g.xlsx')

#### Tworzenie DataFrame dla danych PM10 2024

In [41]:
ds_pm10_2024.columns = ds_pm10_2024.iloc[0]
df_pm10_2024 = ds_pm10_2024.iloc[5:]
df_pm10_2024 = df_pm10_2024[['Kod stacji','LdLodzCzerni','WpPoznSzwajc']]
df_pm10_2024 = df_pm10_2024.rename(columns={'Kod stacji':'Date_time',
                                            'LdLodzCzerni':'LdLodzCzerni_PM10',
                                            'WpPoznSzwajc':'WpPoznSzwajc_PM10'})
df_pm10_2024['Date_time'] = pd.to_datetime(df_pm10_2024['Date_time'])

print(df_pm10_2024.info())
print('\n','='*140,'\n')
display(ds_pm10_2024.iloc[5:7])
display(df_pm10_2024.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 5 to 8788
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date_time          8784 non-null   datetime64[ns]
 1   LdLodzCzerni_PM10  8285 non-null   object
 2   WpPoznSzwajc_PM10  8228 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 206.0+ KB
None

 ============================================================================================================================================

,Kod stacji,DsWrocWybCon,LdLodzCzerni,LdLodzGdansk,MpKrakAlKras,MpKrakBujaka,MpKrakBulwar,MpKrakOsPias,MpKrakSwoszo,MpKrakWadow,...,MzWarBajkowa,MzWarChrosci,MzWarKondrat,MzWarTolstoj,MzWarWokalna,WpPoznDabrow,WpPoznSzwajc,ZpSzczAndrze,ZpSzczecPrze,ZpSzczPilsud
5,2024-01-01 01:00:00,66.9,48,138.9,92.6,194.4,50.5,209.7,81.4,46.9,...,44.4,56.9,93.2,91,55.9,41.5,72.3,68.8,31.3,76.4
6,2024-01-01 02:00:00,49.3,44,164.8,78.5,195.9,64,103.8,125.8,82,...,35.2,34.6,54.5,64.6,49,38.5,93.2,21.3,33.2,31.9

0           Date_time LdLodzCzerni_PM10 WpPoznSzwajc_PM10
5 2024-01-01 01:00:00                48              72.3
6 2024-01-01 02:00:00                44              93.2

#### Tworzenie DataFrame dla danych PM25 2024

In [43]:
ds_pm25_2024.columns = ds_pm25_2024.iloc[0]
df_pm25_2024 = ds_pm25_2024.iloc[5:]
df_pm25_2024 = df_pm25_2024[['Kod stacji','LdLodzCzerni','WpPoznSzwajc']]
df_pm25_2024 = df_pm25_2024.rename(columns={'Kod stacji':'Date_time',
                                           'LdLodzCzerni':'LdLodzCzerni_PM25',
                                            'WpPoznSzwajc':'WpPoznSzwajc_PM25'})
df_pm25_2024['Date_time'] = pd.to_datetime(df_pm25_2024['Date_time'])

print(df_pm25_2024.info())
print('\n','='*140,'\n')
display(ds_pm25_2024.iloc[5:7])
display(df_pm25_2024.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 5 to 8788
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date_time          8784 non-null   datetime64[ns]
 1   LdLodzCzerni_PM25  8264 non-null   object
 2   WpPoznSzwajc_PM25  8228 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 206.0+ KB
None

 ============================================================================================================================================

0           Kod stacji LdLodzCzerni WpPoznDabrow WpPoznSzwajc
5  2024-01-01 01:00:00         43.2         41.3         67.9
6  2024-01-01 02:00:00         39.2         38.4         88.7

0           Date_time LdLodzCzerni_PM25 WpPoznSzwajc_PM25
5 2024-01-01 01:00:00              43.2              67.9
6 2024-01-01 02:00:00              39.2              88.7

#### Tworzenie DataFrame dla danych NO2 2024

In [45]:
ds_no2_2024.columns = ds_no2_2024.iloc[0]
df_no2_2024 = ds_no2_2024.iloc[6:]
df_no2_2024 = df_no2_2024[['Kod stacji','LdLodzCzerni','WpPoznSzwajc']]
df_no2_2024 = df_no2_2024.rename(columns={'Kod stacji':'Date_time',
                                          'LdLodzCzerni':'LdLodzCzerni_NO2',
                                          'WpPoznSzwajc':'WpPoznSzwajc_NO2'})
df_no2_2024['Date_time'] = pd.to_datetime(df_no2_2024['Date_time'])
print(df_no2_2024.info())
print('\n','='*140,'\n')
display(ds_no2_2024.iloc[6:8])
display(df_no2_2024.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8783 entries, 6 to 8788
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date_time         8783 non-null   datetime64[ns]
 1   LdLodzCzerni_NO2  8757 non-null   object
 2   WpPoznSzwajc_NO2  8687 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 206.0+ KB
None

 ============================================================================================================================================

,Kod stacji,LdLodzCzerni,LdLodzGdansk,LdLodzJanPaw,WpPoznDabrow,WpPoznSzwajc
6,2024-01-01 02:00:00,10.2,23.2,27,28,19.8
7,2024-01-01 03:00:00,12.4,25,24.6,25.2,22

0           Date_time LdLodzCzerni_NO2 WpPoznSzwajc_NO2
6 2024-01-01 02:00:00             10.2             19.8
7 2024-01-01 03:00:00             12.4               22

#### Tworzenie DataFrame dla danych CO 2024

In [47]:
# UWAGA: Dla pomiarów CO w Poznaniu w 2024 nie ma danych ze stacji WpPoznSzwajc tylko sa ze stacji WpPoznDobrow
#        Dla usprawnienia daslszych agregacji  zapisujemy nazwę stacji w formie uproszczonej WpPozn_CO (bez rozróżnienia
#        która stacja odpowiada za pomiar CO w latach 2023 i 2024)

ds_co_2024.columns = ds_co_2024.iloc[0]
df_co_2024 = ds_co_2024.iloc[5:]
df_co_2024 = df_co_2024[['Kod stacji','LdLodzJanPaw','WpPoznDabrow']]
df_co_2024 = df_co_2024.rename(columns={'Kod stacji':'Date_time',
                                        'LdLodzJanPaw':'LdLodzJanPaw_CO',
                                        'WpPoznDabrow':'WpPozn_CO'})
df_co_2024['Date_time'] = pd.to_datetime(df_co_2024['Date_time'])
print(df_co_2024.info())
print('\n','='*140,'\n')
display(ds_co_2024.iloc[5:7])
display(df_co_2024.head(2))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 5 to 8788
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date_time        8784 non-null   datetime64[ns]
 1   LdLodzJanPaw_CO  8759 non-null   object
 2   WpPozn_CO        8654 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 206.0+ KB
None

 ============================================================================================================================================

0           Kod stacji LdLodzJanPaw WpPoznDabrow
5  2024-01-01 01:00:00        0.682        0.621
6  2024-01-01 02:00:00        0.783        0.668

0           Date_time LdLodzJanPaw_CO WpPozn_CO
5 2024-01-01 01:00:00           0.682     0.621
6 2024-01-01 02:00:00           0.783     0.668

#### Merge Wszyskich DataSetów 2024 + Eksport do cvs

In [49]:
from functools import reduce

dfs_list_2024 = [df_pm10_2024, df_pm25_2024, df_no2_2024, df_co_2024]

df_polution_2024_merged = reduce(lambda left, right: left.merge(right, on="Date_time", how="left"), dfs_list_2024)

# Eksport do pliku w raw data
df_polution_2024_merged.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/data_polution_2024')