In [7]:
# !pip install cdsapi
# !pip install eccodes
# !pip install cfgrib eccodes
# !conda install -c conda-forge eccodes cfgrib xarray -y

### INWERSJA - POZNAŃ 2021

In [4]:
import cdsapi

dataset = "reanalysis-era5-pressure-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": ["temperature"],
    "year": ["2021"],
    "month": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "pressure_level": ["925", "1000"],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [52.54000, 16.80000, 52.28000, 17.06000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-05-11 17:09:09,343 INFO Request ID is 582b4fc5-85f4-47d2-b52d-4cec4eab88b3
2026-05-11 17:09:09,474 INFO status has been updated to accepted
2026-05-11 17:21:35,014 INFO status has been updated to running
2026-05-11 17:25:35,673 INFO status has been updated to successful

fc78cabb2de5c658ef01917cadeeca75.grib:   0%|          | 0.00/314k [00:00<?, ?B/s]

'fc78cabb2de5c658ef01917cadeeca75.grib'

In [10]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
ds_i_pz_2021 = xr.open_dataset(
    'fc78cabb2de5c658ef01917cadeeca75.grib',
    engine='cfgrib'
)

print(ds_i_pz_2021)

import pandas as pd

df_i_pz_2021 = ds_i_pz_2021.to_dataframe().reset_index()
df_i_pz_2021.head()

# EKSPORT DO PLIKU CSV 

df_i_pz_2021.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/inwersja_pz_2021.csv')

<xarray.Dataset> Size: 35kB
Dimensions:        (time: 1460, isobaricInhPa: 2, latitude: 1, longitude: 1)
Coordinates:
  * time           (time) datetime64[ns] 12kB 2021-01-01 ... 2021-12-31T18:00:00
    valid_time     (time) datetime64[ns] 12kB ...
  * isobaricInhPa  (isobaricInhPa) float64 16B 1e+03 925.0
  * latitude       (latitude) float64 8B 52.5
  * longitude      (longitude) float64 8B 17.0
    number         int64 8B ...
    step           timedelta64[ns] 8B ...
Data variables:
    t              (time, isobaricInhPa, latitude, longitude) float32 12kB ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-05-11T19:46 GRIB to CDM+CF via cfgrib-0.9.1...

### INWERSJA - POZNAŃ 2022

In [5]:
import cdsapi

dataset = "reanalysis-era5-pressure-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": ["temperature"],
    "year": ["2022"],
    "month": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "pressure_level": ["925", "1000"],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [52.54000, 16.80000, 52.28000, 17.06000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-05-11 17:25:38,000 INFO Request ID is 5b9e7780-5cd5-479c-89b5-667700effc36
2026-05-11 17:25:38,119 INFO status has been updated to accepted
2026-05-11 17:44:01,501 INFO status has been updated to running
2026-05-11 17:48:02,626 INFO status has been updated to successful

a4eaec431c1f948312ab7f1ea7ebcd8.grib:   0%|          | 0.00/314k [00:00<?, ?B/s]

'a4eaec431c1f948312ab7f1ea7ebcd8.grib'

In [8]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
ds_i_pz_2022 = xr.open_dataset(
    'a4eaec431c1f948312ab7f1ea7ebcd8.grib',
    engine='cfgrib'
)

print(ds_i_pz_2022)

import pandas as pd

df_i_pz_2022 = ds_i_pz_2022.to_dataframe().reset_index()
df_i_pz_2022.head()

# EKSPORT DO PLIKU CSV 

df_i_pz_2022.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/inwersja_pz_2022.csv')

<xarray.Dataset> Size: 35kB
Dimensions:        (time: 1460, isobaricInhPa: 2, latitude: 1, longitude: 1)
Coordinates:
  * time           (time) datetime64[ns] 12kB 2022-01-01 ... 2022-12-31T18:00:00
    valid_time     (time) datetime64[ns] 12kB ...
  * isobaricInhPa  (isobaricInhPa) float64 16B 1e+03 925.0
  * latitude       (latitude) float64 8B 52.5
  * longitude      (longitude) float64 8B 17.0
    number         int64 8B ...
    step           timedelta64[ns] 8B ...
Data variables:
    t              (time, isobaricInhPa, latitude, longitude) float32 12kB ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-05-11T19:46 GRIB to CDM+CF via cfgrib-0.9.1...

### INWERSJA - POZNAŃ 2023

In [ ]:
import cdsapi

dataset = "reanalysis-era5-pressure-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": ["temperature"],
    "year": ["2023"],
    "month": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "pressure_level": ["925", "1000"],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [52.54000, 16.80000, 52.28000, 17.06000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

In [6]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
ds_i_pz_2023 = xr.open_dataset(
    '2886a49bedd5282dfbe02818bd25edc3.grib',
    engine='cfgrib'
)

print(ds_i_pz_2023)

<xarray.Dataset> Size: 168B
Dimensions:        (time: 5, isobaricInhPa: 2, latitude: 1, longitude: 1)
Coordinates:
  * time           (time) datetime64[ns] 40B 2023-01-01 ... 2023-01-02
    valid_time     (time) datetime64[ns] 40B ...
  * isobaricInhPa  (isobaricInhPa) float64 16B 1e+03 925.0
  * latitude       (latitude) float64 8B 52.5
  * longitude      (longitude) float64 8B 17.0
    number         int64 8B ...
    step           timedelta64[ns] 8B ...
Data variables:
    t              (time, isobaricInhPa, latitude, longitude) float32 40B ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-05-01T15:50 GRIB to CDM+CF via cfgrib-0.9.1...

In [10]:
import pandas as pd

df_i_pz_2023 = ds_i_pz_2023.to_dataframe().reset_index()
df_i_pz_2023.head()

,time,isobaricInhPa,latitude,longitude,number,step,valid_time,t
0,2023-01-01 00:00:00,1000.0,52.5,17.0,0,0 days,2023-01-01 00:00:00,288.558350
1,2023-01-01 00:00:00,925.0,52.5,17.0,0,0 days,2023-01-01 00:00:00,285.520508
2,2023-01-01 06:00:00,1000.0,52.5,17.0,0,0 days,2023-01-01 06:00:00,287.873779
3,2023-01-01 06:00:00,925.0,52.5,17.0,0,0 days,2023-01-01 06:00:00,285.555420
4,2023-01-01 12:00:00,1000.0,52.5,17.0,0,0 days,2023-01-01 12:00:00,288.744141

In [14]:
# EKSPORT DO PLIKU CSV 

# df_i_pz_2023.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/inwersja_pz_2023.csv')

### API INWERSJA - Poznań 2024

In [21]:
import cdsapi

dataset = "reanalysis-era5-pressure-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": ["temperature"],
    "year": ["2024"],
    "month": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "pressure_level": ["925", "1000"],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [52.54000, 16.80000, 52.28000, 17.06000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-05-01 15:57:56,897 INFO Request ID is 734cfe2a-7b51-4060-8875-0aec69749619
2026-05-01 15:57:57,017 INFO status has been updated to accepted
2026-05-01 15:58:08,037 INFO status has been updated to running
2026-05-01 16:02:19,978 INFO status has been updated to successful

e08c9719a281ae54244a8507cda4f64c.grib:   0%|          | 0.00/315k [00:00<?, ?B/s]

'e08c9719a281ae54244a8507cda4f64c.grib'

In [23]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
i_pz_2024_ds = xr.open_dataset(
    'e08c9719a281ae54244a8507cda4f64c.grib',
    engine='cfgrib'
)

In [25]:
import pandas as pd

i_pz_2024_df = i_pz_2024_ds.to_dataframe().reset_index()


# # Wyświetl wszystkie wiersze i kolumny
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)

print(i_pz_2024_df.shape)  # ile wierszy x kolumn
i_pz_2024_df.head()

(2928, 8)

,time,isobaricInhPa,latitude,longitude,number,step,valid_time,t
0,2024-01-01 00:00:00,1000.0,52.5,17.0,0,0 days,2024-01-01 00:00:00,279.217041
1,2024-01-01 00:00:00,925.0,52.5,17.0,0,0 days,2024-01-01 00:00:00,277.268555
2,2024-01-01 06:00:00,1000.0,52.5,17.0,0,0 days,2024-01-01 06:00:00,279.074219
3,2024-01-01 06:00:00,925.0,52.5,17.0,0,0 days,2024-01-01 06:00:00,276.662842
4,2024-01-01 12:00:00,1000.0,52.5,17.0,0,0 days,2024-01-01 12:00:00,279.577881

In [29]:
# Eksport do pliku csv.

# i_pz_2024_df.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/inwersja_pz_2024.csv')

In [9]:
# import pandas as pd

# # Konwersja do DataFrame (temperatura w Kelvinach -> Celsjusze)
# df = ds['t'].to_dataframe().reset_index()
# df['temperature_C'] = df['t'] - 273.15

# print(df.head(20))
# print(f"\nZakres dat: {df['time'].min()} → {df['time'].max()}")
# print(f"Poziomy ciśnienia: {df['isobaricInhPa'].unique()}")

                  time  isobaricInhPa  number   step  latitude  longitude  \
0  2024-01-01 00:00:00         1000.0       0 0 days      53.5       14.5
1  2024-01-01 00:00:00          925.0       0 0 days      53.5       14.5
2  2024-01-01 06:00:00         1000.0       0 0 days      53.5       14.5
3  2024-01-01 06:00:00          925.0       0 0 days      53.5       14.5
4  2024-01-01 12:00:00         1000.0       0 0 days      53.5       14.5
5  2024-01-01 12:00:00          925.0       0 0 days      53.5       14.5
6  2024-01-01 18:00:00         1000.0       0 0 days      53.5       14.5
7  2024-01-01 18:00:00          925.0       0 0 days      53.5       14.5
8  2024-01-02 00:00:00         1000.0       0 0 days      53.5       14.5
9  2024-01-02 00:00:00          925.0       0 0 days      53.5       14.5
10 2024-01-02 06:00:00         1000.0       0 0 days      53.5       14.5
11 2024-01-02 06:00:00          925.0       0 0 days      53.5       14.5
12 2024-01-02 12:00:00         1000.0       0 0 days      53.5       14.5
13 2024-01-02 12:00:00          925.0       0 0 days      53.5       14.5
14 2024-01-02 18:00:00         1000.0       0 0 days      53.5       14.5
15 2024-01-02 18:00:00          925.0       0 0 days      53.5       14.5
16 2024-01-03 00:00:00         1000.0       0 0 days      53.5       14.5
17 2024-01-03 00:00:00          925.0       0 0 days      53.5       14.5
18 2024-01-03 06:00:00         1000.0       0 0 days      53.5       14.5
19 2024-01-03 06:00:00          925.0       0 0 days      53.5       14.5

            valid_time           t  temperature_C
0  2024-01-01 00:00:00  278.467041       5.317047
1  2024-01-01 00:00:00  277.290039       4.140045
2  2024-01-01 06:00:00  277.591797       4.441803
3  2024-01-01 06:00:00  276.446045       3.296051
4  2024-01-01 12:00:00  279.575928       6.425934
5  2024-01-01 12:00:00  276.466309       3.316315
6  2024-01-01 18:00:00  277.936523       4.786530
7  2024-01-01 18:00:00  274.774902       1.624908
8  2024-01-02 00:00:00  278.418213       5.268219
9  2024-01-02 00:00:00  275.338379       2.188385
10 2024-01-02 06:00:00  277.175049       4.025055
11 2024-01-02 06:00:00  274.102539       0.952545
12 2024-01-02 12:00:00  278.241211       5.091217
13 2024-01-02 12:00:00  274.854492       1.704498
14 2024-01-02 18:00:00  278.005859       4.855865
15 2024-01-02 18:00:00  273.816406       0.666412
16 2024-01-03 00:00:00  277.254883       4.104889
17 2024-01-03 00:00:00  275.951172       2.801178
18 2024-01-03 06:00:00  282.969727       9.819733
19 2024-01-03 06:00:00  279.289795       6.139801

Zakres dat: 2024-01-01 00:00:00 → 2024-12-31 18:00:00
Poziomy ciśnienia: [1000.  925.]

## API INWERSJA - ŁÓDŹ 2023

In [ ]:
import cdsapi

dataset = "reanalysis-era5-pressure-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": ["temperature"],
    "year": ["2023"],
    "month": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "pressure_level": ["925", "1000"],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [51.91000, 19.33000, 51.64000, 19.59000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

In [31]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
ds_i_ld_2023 = xr.open_dataset(
    '1b28650d2dd1a0766896ed79e643b383.grib',
    engine='cfgrib'
)

print(ds_i_ld_2023)

<xarray.Dataset> Size: 35kB
Dimensions:        (time: 1460, isobaricInhPa: 2, latitude: 1, longitude: 1)
Coordinates:
  * time           (time) datetime64[ns] 12kB 2023-01-01 ... 2023-12-31T18:00:00
    valid_time     (time) datetime64[ns] 12kB ...
  * isobaricInhPa  (isobaricInhPa) float64 16B 1e+03 925.0
  * latitude       (latitude) float64 8B 51.75
  * longitude      (longitude) float64 8B 19.5
    number         int64 8B ...
    step           timedelta64[ns] 8B ...
Data variables:
    t              (time, isobaricInhPa, latitude, longitude) float32 12kB ...
Attributes:
    GRIB_edition:            1
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-05-01T16:11 GRIB to CDM+CF via cfgrib-0.9.1...

In [33]:
import pandas as pd

df_i_ld_2023 = ds_i_ld_2023.to_dataframe().reset_index()

# # Wyświetl wszystkie wiersze i kolumny
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
# pd.set_option('display.width', None)

print(df_i_ld_2023.shape)  # ile wierszy x kolumn
df_i_ld_2023.head()

(2920, 8)

,time,isobaricInhPa,latitude,longitude,number,step,valid_time,t
0,2023-01-01 00:00:00,1000.0,51.75,19.5,0,0 days,2023-01-01 00:00:00,287.689209
1,2023-01-01 00:00:00,925.0,51.75,19.5,0,0 days,2023-01-01 00:00:00,286.381836
2,2023-01-01 06:00:00,1000.0,51.75,19.5,0,0 days,2023-01-01 06:00:00,287.905029
3,2023-01-01 06:00:00,925.0,51.75,19.5,0,0 days,2023-01-01 06:00:00,285.934326
4,2023-01-01 12:00:00,1000.0,51.75,19.5,0,0 days,2023-01-01 12:00:00,289.496094

In [45]:
# EKSPORT DO PLIKU CSV 

df_i_ld_2023.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/inwersja_ld_2023.csv')

## API INWERSJA - ŁÓDŹ 2024

In [6]:
import cdsapi

dataset = "reanalysis-era5-pressure-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": ["temperature"],
    "year": ["2024"],
    "month": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12"
    ],
    "day": [
        "01", "02", "03",
        "04", "05", "06",
        "07", "08", "09",
        "10", "11", "12",
        "13", "14", "15",
        "16", "17", "18",
        "19", "20", "21",
        "22", "23", "24",
        "25", "26", "27",
        "28", "29", "30",
        "31"
    ],
    "time": [
        "00:00", "06:00", "12:00",
        "18:00"
    ],
    "pressure_level": ["925", "1000"],
    "data_format": "grib",
    "download_format": "unarchived",
    "area": [51.91000, 19.33000, 51.64000, 19.59000]
}

client = cdsapi.Client(
    url = "https://cds.climate.copernicus.eu/api",
    key = "f55a5040-c43c-40a7-957a-f078b44210f3"
)
client.retrieve(dataset, request).download()

2026-04-09 18:56:25,174 INFO Request ID is ca243b6b-d8f2-436f-a479-627a92072d4e
2026-04-09 18:56:25,274 INFO status has been updated to accepted
2026-04-09 19:04:46,670 INFO status has been updated to running
2026-04-09 19:08:47,780 INFO status has been updated to successful

ea8be334f68d71b85bef2da9a8803572.grib:   0%|          | 0.00/315k [00:00<?, ?B/s]

'ea8be334f68d71b85bef2da9a8803572.grib'

In [39]:
import eccodes
import xarray as xr
import cfgrib

# Odczyt pliku GRIB przez xarray
i_ld_2024_ds = xr.open_dataset(
    'ea8be334f68d71b85bef2da9a8803572.grib',
    engine='cfgrib'
)

import pandas as pd
i_ld_2024_df = i_ld_2024_ds.to_dataframe().reset_index()

# Wyświetl wszystkie wiersze i kolumny
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

print(i_ld_2024_df.shape)  # ile wierszy x kolumn
i_ld_2024_df.head()

(2928, 8)

,time,isobaricInhPa,latitude,longitude,number,step,valid_time,t
0,2024-01-01 00:00:00,1000.0,51.75,19.5,0,0 days,2024-01-01 00:00:00,280.791260
1,2024-01-01 00:00:00,925.0,51.75,19.5,0,0 days,2024-01-01 00:00:00,277.645508
2,2024-01-01 06:00:00,1000.0,51.75,19.5,0,0 days,2024-01-01 06:00:00,279.488281
3,2024-01-01 06:00:00,925.0,51.75,19.5,0,0 days,2024-01-01 06:00:00,276.463623
4,2024-01-01 12:00:00,1000.0,51.75,19.5,0,0 days,2024-01-01 12:00:00,278.585693

In [71]:
# Rozdzielam na dwa DataFrame 
df_inwersja_ld_2024_925 = df_inwersja_ld_2024[df_inwersja_ld_2024['isobaricInhPa'] == 925][['time','t']].rename(columns = {'t': 't_925'})
df_inwersja_ld_2024_1000 = df_inwersja_ld_2024[df_inwersja_ld_2024['isobaricInhPa'] == 1000][['time','t']].rename(columns = {'t': 't_1000'})

# Łaczymy oba df, w jeden do obliczenia różnicy
df_inwersja_ld_2024_delta = pd.merge(df_inwersja_ld_2024_925, df_inwersja_ld_2024_1000, how='inner', on='time')

# kolumna t_delta = podaje rożnice w stopniach 
df_inwersja_ld_2024_delta['t_delta'] = df_inwersja_ld_2024_delta['t_1000']-df_inwersja_ld_2024_delta['t_925']
df_inwersja_ld_2024_delta['inversion_0/1'] = [1 if e > 0 else 0 for e in df_inwersja_ld_2024_delta['t_delta']]

# wyciagamy sama date , do łatiwejszegeo grupowania i wyciagniecia dziennej sreniej 

df_inwersja_ld_2024_delta['data'] = df_inwersja_ld_2024_delta['time'].dt.date
df_inwersja_ld_2024_delta['city'] = 'ld'
df_inwersja_ld_2024_delta.head()

,time,t_925,t_1000,t_delta,inversion_0/1,data,city
0,2024-01-01 00:00:00,277.645508,280.791260,3.145752,1,2024-01-01,ld
1,2024-01-01 06:00:00,276.463623,279.488281,3.024658,1,2024-01-01,ld
2,2024-01-01 12:00:00,274.171387,278.585693,4.414307,1,2024-01-01,ld
3,2024-01-01 18:00:00,275.126465,278.893555,3.767090,1,2024-01-01,ld
4,2024-01-02 00:00:00,274.584473,278.025635,3.441162,1,2024-01-02,ld

In [43]:
# Eksport do pliku csv.

i_ld_2024_df.to_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/inwersja_ld_2024.csv')