# PROJEKT : <span style="margin-left:40px;"> Jerzy Marcin Urbański</span>

##### TEMAT:
## Analiza Jakości Powietrza Dla Wybranych Lokalizacji Oraz Okresów

Importy Bibliotek wraz z ich opisem

In [5]:
# ### pandas

# Biblioteka do pracy z danymi tabelarycznymi (DataFrame), umożliwia łatwe filtrowanie, grupowanie i przekształcanie danych. 
# Używana głównie do analizy danych, czyszczenia danych oraz wczytywania/zapisywania plików (CSV, Excel, SQL).
import pandas as pd

# ### numpy
# Podstawowa biblioteka do obliczeń numerycznych w Pythonie, oferująca wydajne operacje na tablicach wielowymiarowych. 
# Wykorzystywana do obliczeń matematycznych, statystycznych oraz jako fundament dla innych bibliotek analitycznych.
import numpy as np

# ### os
# Biblioteka standardowa do interakcji z systemem operacyjnym, umożliwia pracę z plikami i katalogami oraz zmiennymi środowiskowymi. 
#Używana m.in. do automatyzacji operacji na plikach i zarządzania ścieżkami.
import os

# ### matplotlib
# Biblioteka do tworzenia wykresów i wizualizacji danych w Pythonie. Pozwala generować różne typy wykresów (liniowe, słupkowe, histogramy) 
# oraz dostosowywać ich wygląd.
import matplotlib.pyplot as plt

# ### seaborn
# Rozszerzenie matplotlib, które upraszcza tworzenie estetycznych i statystycznych wizualizacji danych. 
# Umożliwia szybkie generowanie wykresów takich jak heatmapy, wykresy rozkładu czy zależności między zmiennymi.
import seaborn as sns

# ### ydata_profiling
# Biblioteka do automatycznej analizy eksploracyjnej danych (EDA), generująca szczegółowe raporty o zbiorze danych. 
# Pokazuje statystyki, brakujące wartości, korelacje i potencjalne problemy w danych.
from ydata_profiling import ProfileReport

# ### IPython.display
# Moduł umożliwiający wyświetlanie różnych typów treści w notebookach (HTML, obrazy, wideo). 
#  Używany do wzbogacania prezentacji wyników analiz i tworzenia interaktywnych raportów.
from IPython.display import IFrame
from pathlib import Path

## STEP 1.
Import danych z plików csv , ostateczne sprawdznie oraz potrzebna agregacja do ostatecznej wersji.

### 1.2 - Tabele Pogodowe - ready_weather[...]

##### 1.2.1. Import wszyskich plików do odpowiednich zmiennych

In [9]:
# import wszyskich plików do odpowiednich zmiennych 

w_ld_2004 = pd.read_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/ready_weather_ld_2004.csv')
w_ld_2024 = pd.read_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/ready_weather_ld_2024.csv')
w_pz_2004 = pd.read_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/ready_weather_pz_2004.csv')
w_pz_2024 = pd.read_csv('/Users/marcinurbanski/Desktop/jmu_repo/1_projekt_air_polution_repo/0_ready_raw_data/ready_weather_pz_2024.csv')

In [10]:
# szybkie sprawdznie 

display(w_ld_2004.head(2))
# display(w_ld_2024.head(2))
# display(w_pz_2004.head(2))
# display(w_pz_2024.head(2))

,Unnamed: 0,time,latitude,longitude,number,step,surface,valid_time,u10,v10,t2m,blh,sp,tcc
0,0,2004-01-01 00:00:00,51.75,19.5,0,0 days,0.0,2004-01-01 00:00:00,0.794144,-3.466965,272.89502,413.98730,99670.00,0.989990
1,1,2004-01-01 06:00:00,51.75,19.5,0,0 days,0.0,2004-01-01 06:00:00,0.833252,-3.170166,271.41577,404.84766,99482.06,0.983978

#### 1.2.2 - Agregacja danych do postaci uniwersalnego DataFrame

In [12]:
# usunięcie niepotrzebnych kolumn ['Unnamed: 0','latitude','longitude','step','surface','valid_time']

In [13]:
# Selekscja kolumn do usunięcia 

# print(w_ld_2004['step'].nunique()) # kolumna ma jeden wynik -> usunać
# print('-'*140)
# print(w_ld_2004['surface'].nunique()) # kolumna ma jeden wynik -> usunać
# print('-'*140)
# print(w_ld_2004[w_ld_2004["time"] != w_ld_2004["valid_time"]]) # kolumna 'valid_time' powtrza wartosci 'time' -> usunać 
# print('-'*140)
# print(w_ld_2004['number'].nunique())

In [14]:
# Usunięcie kolumn bez wartości dla dalszej analizy.

w_ld_2004 = w_ld_2004.drop(['Unnamed: 0','latitude','longitude','step','surface','valid_time','number'], axis=1)
w_ld_2024 = w_ld_2024.drop(['Unnamed: 0','latitude','longitude','step','surface','valid_time','number'], axis=1)
w_pz_2004 = w_pz_2004.drop(['Unnamed: 0','latitude','longitude','step','surface','valid_time','number'], axis=1)
w_pz_2024 = w_pz_2024.drop(['Unnamed: 0','latitude','longitude','step','surface','valid_time','number'], axis=1)

In [15]:
w_ld_2004['time'] = pd.to_datetime(w_ld_2004['time'])
w_ld_2024['time'] = pd.to_datetime(w_ld_2024['time'])
w_pz_2004['time'] = pd.to_datetime(w_pz_2004['time'])
w_pz_2024['time'] = pd.to_datetime(w_pz_2024['time'])

In [22]:
w_ld_2004['city'] = 'PZ'
w_ld_2024['city'] = 'PZ'
w_pz_2004['city'] = 'PZ'
w_pz_2024['city'] = 'PZ'
w_pz_2024.head()

,time,u10,v10,t2m,blh,sp,tcc,city
0,2024-01-01 00:00:00,0.916779,2.373703,276.52270,171.43484,99595.56,1.000000,PZ
1,2024-01-01 06:00:00,2.034958,1.306549,276.30347,164.58713,99511.75,1.000000,PZ
2,2024-01-01 12:00:00,3.338638,1.055939,278.74780,529.93410,99504.81,1.000000,PZ
3,2024-01-01 18:00:00,3.177460,0.872955,277.53662,409.93090,99615.31,0.695404,PZ
4,2024-01-02 00:00:00,3.800644,1.477478,277.71387,467.85132,99671.06,0.946899,PZ

In [42]:
# Rozbicie daty/godziny 'time' na szczegóły i zapisanie w nowych kolumnach 
    #zamiana wartości w kolumnie 'time' na typ datetime
w_ld_2004['time'] = pd.to_datetime(w_ld_2004['time'])
w_ld_2024['time'] = pd.to_datetime(w_ld_2024['time'])
w_pz_2004['time'] = pd.to_datetime(w_pz_2004['time'])
w_pz_2024['time'] = pd.to_datetime(w_pz_2024['time'])

w_ld_2004 = w_ld_2004.assign(
    month=w_ld_2004['time'].dt.month_name(),
    year=w_ld_2004['time'].dt.year,
    day=w_ld_2004['time'].dt.day,
    day_of_week=w_ld_2004['time'].dt.day_name())

w_ld_2024 = w_ld_2024.assign(
    month=w_ld_2024['time'].dt.month_name(),
    year=w_ld_2024['time'].dt.year,
    day=w_ld_2024['time'].dt.day,
    day_of_week=w_ld_2024['time'].dt.day_name())

w_pz_2004 = w_pz_2004.assign(
    month=w_pz_2004['time'].dt.month_name(),
    year=w_pz_2004['time'].dt.year,
    day=w_pz_2004['time'].dt.day,
    day_of_week=w_pz_2004['time'].dt.day_name()) 

w_pz_2024 = w_pz_2024.assign(
    month=w_pz_2024['time'].dt.month_name(),
    year=w_pz_2024['time'].dt.year,
    day=w_pz_2024['time'].dt.day,
    day_of_week=w_pz_2024['time'].dt.day_name())

In [48]:
w_pz_2024.head()

,time,u10,v10,t2m,blh,sp,tcc,city,month,year,day,day_of_week
0,2024-01-01 00:00:00,0.916779,2.373703,276.52270,171.43484,99595.56,1.000000,PZ,January,2024,1,Monday
1,2024-01-01 06:00:00,2.034958,1.306549,276.30347,164.58713,99511.75,1.000000,PZ,January,2024,1,Monday
2,2024-01-01 12:00:00,3.338638,1.055939,278.74780,529.93410,99504.81,1.000000,PZ,January,2024,1,Monday
3,2024-01-01 18:00:00,3.177460,0.872955,277.53662,409.93090,99615.31,0.695404,PZ,January,2024,1,Monday
4,2024-01-02 00:00:00,3.800644,1.477478,277.71387,467.85132,99671.06,0.946899,PZ,January,2024,2,Tuesday

#### Obliczenie prędkości wiatru ze zmiennych u10 & v10 ze wzoru tj z równania pitagorasa
- zmienna u10 => prędkość wiatru zachodniego 
- zmienna v10 => prędkość wiartu północnego 

$$
v_w = \sqrt{u_{10}^2 + v_{10}^2}
$$

In [60]:
# przeliczenie prędkości wiatru 'v_w' dla wszyskich DataFrame pogodowych i dodanie jako nowa kolumna z tymi wartościami

w_ld_2004['v_w'] = np.sqrt(w_ld_2004['u10']**2 + w_ld_2004['v10']**2)
w_ld_2024['v_w'] = np.sqrt(w_ld_2024['u10']**2 + w_ld_2024['v10']**2)
w_pz_2004['v_w'] = np.sqrt(w_pz_2004['u10']**2 + w_pz_2004['v10']**2)
w_pz_2024['v_w'] = np.sqrt(w_pz_2024['u10']**2 + w_pz_2024['v10']**2)

In [80]:
# ułożenie kolejnosci kolumn [info data | zmienne pogodowe] 

col_order = ['city','time','year','month','day','day_of_week','u10', 'v10','v_w','t2m','blh','sp','tcc']
w_ld_2004 = w_ld_2004[col_order]
w_ld_2024 = w_ld_2024[col_order]
w_pz_2004 = w_pz_2004[col_order]
w_pz_2024 = w_pz_2024[col_order]

####  1.2.3. Połaczenie wszystkich Data Frame w jeden pogodowy

In [87]:
w_df = pd.concat([w_ld_2004,w_ld_2024,w_pz_2004,w_pz_2024], axis=0 , ignore_index=True)